### ISSUE TITLE
Tracing bad yaml code - eval_builtin_error: json.unmarshal: invalid character ']' 

### ISSUE THREAD

**Issue by jmcdon01** [doitintl/kube-no-trouble#13]
Thank you for this fantastic tool!

This has worked in several clusters, but in one I receive this message. It may be indicative of some odd yaml somewhere in our cluster, but I'm not sure how to trace it, and since it's being retrieved from the cluster it suggests that it may be valid yaml but misinterpreted. Also the rule returned whether 1.16/1.20 rotates randomly between the 2, and --debug doesn't seem to print any more to screen.

$ kubent --debug -k ~/Kubeconfig-prd1 --helm2=false --helm3=false 
10:38AM INF >>> Kube No Trouble `kubent` <<<
10:38AM INF version 0.2.0 (git sha b9b45f347c7e67cf488d8dd6e20c8b848c595a3e)
10:38AM INF Initializing collectors and retrieving data
10:38AM INF Retrieved 3843 resources from collector name=Cluster
10:38AM INF Loaded ruleset name=deprecated-1-16.rego
10:38AM INF Loaded ruleset name=deprecated-1-20.rego
10:38AM FTL Failed to evaluate input error="deprecated-1-16.rego:14: eval_builtin_error: json.unmarshal: invalid character ']' after object key:value pair" name=Rego

**Comment by stepanstipl** [comment]
Hi @jmcdon01,
thanks, glad to hear you found the tool useful 🚀, and thanks for reporting this issue 👍.

I think the issue will be that one of the K8s resources will have invalid json in the `kubectl.kubernetes.io/last-applied-configuration` annotation, which is used to detect API version used to create the resource (or json that rego library is not able to parse).

Currently, the resources are evaluated all at once, so that makes it a bit tricky to pinpoint the one causing the parsing to fail. But now that I'm aware of this possible issue, I'll have a look at how this use case can be improved, to at least print some useful error/debug message to pin down the problematic resource, and also continue processing the rest if possible.

Thanks, and I'll update this issue.

**Comment by stepanstipl** [comment]
@jmcdon01 the improvement on this has now been merged and release, please try the latest [0.3.0](https://github.com/doitintl/kube-no-trouble/releases/tag/0.3.0) release.

It should now print more details about the resource if failed to parse, such as:
```
6:07PM ERR Failed to retrieve data from collector error="failed to parse last-applied-configuration annotation of resource default/test-ingress: invalid character '{' looking for beginning of object key s
tring" name=Cluster
```

**Comment by jmcdon01** [comment]
Thanks Stepan,

That was useful in finding the issue, an ingress definition in
last-applied-configuration with
"servicePort":5000}]}}]}}
instead of
"servicePort":5000}}]}}]}}
so that the json was invalid for a parser. Somehow it seems Kubernetes was
OK with it though.

However, for some reason now, the number of resources pulled from the
clusters is much reduced. With the old version on one cluster I got 3000
and now I get 300.

John.

**Comment by david-doit-intl** [comment]
Lets open a new ticket @jmcdon01 about the number of resources.
