### ISSUE TITLE
Installation via homebrew

### ISSUE THREAD

**Issue by olfway** [doitintl/kube-no-trouble#298]
Please add an option to install via homebrew

**Comment by dark0dave** [comment]
Is this really needed? we'd propably prefer you to run this in docker or? I guess I'd like to know more about your usecase

**Comment by dark0dave** [comment]
I prefer you to download the binary supporting homebrew is big pass

**Comment by dark0dave** [comment]
should we also support apt, pacman, etc? It gets out of hand. I am pretty happy with the current state.

**Comment by stepanstipl** [comment]
Hi @olfway, thanks for the suggestion 👍. At the moment I think this is a bit out of scope, as we don't support (and due to limited capacity do not want to take that additional work on atm.) any OS-specific package distribution and management mechanisms.

Homebrew core would require us to build the binaries from the source (so there's a bit of work to do this right), go via the approval process, and mainly maintain the formula in the homebrew core repo. We could support it as a cask, but that requires a separate `homebrew-` prefixed repo.

In any case, at the moment we do not intend to support individual OS-specific package distribution mechanisms, however, this should not stop anyone from contributing this either to homebrew core directly, or via their own cask 🙏  (if you do that, and are willing to maintain this on an ongoing basis, let us know, would be happy to include a note in the readme 😄 ).

But please if there is interest in this, ⭐ ⭐ ⭐  this issue - I have labelled it as `revisit` so that we will revisit and might reconsider supporting this in the future if there's enough interest.

**Comment by devenes** [comment]
Thanks for bringing this up, @olfway. 

We have now included the Homebrew installation method as a third-party option in our README file. Going forward, the community will be responsible for maintaining the formula and ensuring it stays up to date with new releases. For more information, please refer to: [Third-Party Installation via Homebrew](https://github.com/doitintl/kube-no-trouble#third-party-installation).
