### ISSUE TITLE
Support for CRDs

### ISSUE THREAD

**Issue by alexbowers** [doitintl/kube-no-trouble#354]
Is there any planned features for supporting CRDs and their deprecations? I couldn't find anything documented about this

**Comment by alexbowers** [comment]
Prevent stale

**Comment by stepanstipl** [comment]
Hi @alexbowers, thanks for asking. And sorry for not replying sooner, this somehow slipped past me.

How would you imagine this support?

At the moment we support flagging additional kinds:
```
-a, --additional-kind strings         additional kinds of resources to report in Kind.version.group.com format
```
so you can tell kubent to flag any CRDs in certain versions.

I think it's unrealistic that we would track wider range of 3rd party CRDs directly in this project, simply because there are too many. But if you have some specific, more popular ones, in mind, feel free to suggest/open PR (there's no clear cut as to what we want to track, I personally see it as core K8S resources, and ones from major cloud providers - i.e. GCP/AWS/Azure).

Otherwise, the question would be about how to make `kubent` extendable. We already introduced the `-a` flag mentioned above, but I'm open to further suggestions.
