### ISSUE TITLE
Retrieved 0 resources from collector

### ISSUE THREAD

**Issue by csuka** [doitintl/kube-no-trouble#423]
Hi,

I'd like to use your tool, however, the tool outputs it didn't find any resources.

```bash
root@0d62dbe0744b:~# ./kubent --helm2=false --helm3=false
12:52PM INF >>> Kube No Trouble `kubent` <<<
12:52PM INF version 0.6.0 (git sha 126e47b9b45550a45404b599c546bf911ffae571)
12:52PM INF Initializing collectors and retrieving data
12:52PM INF Target K8s version is 1.24.8
12:52PM INF Retrieved 0 resources from collector name=Cluster
12:52PM INF Loaded ruleset name=custom.rego.tmpl
12:52PM INF Loaded ruleset name=deprecated-1-16.rego
12:52PM INF Loaded ruleset name=deprecated-1-22.rego
12:52PM INF Loaded ruleset name=deprecated-1-25.rego
12:52PM INF Loaded ruleset name=deprecated-1-26.rego
12:52PM INF Loaded ruleset name=deprecated-future.rego
```
I can run Kube commands and I am authenticated.
```bash
root@0d62dbe0744b:~# k get ns
NAME                 STATUS   AGE
...
default              Active   20d
...
```
How do I debug this issue and/or can anyone provide me any pointers on how to solve this?

**Comment by stepanstipl** [comment]
Hi @csuka,

thanks for trying out the tool. Kubent will retrieve only certain resources of interest [^1], e.g. Ingress. Do you have any such resources in your cluster?

Otherwise, as to debugging, you can use the `--log-level`/`-l` flag with `debug` or `trace` levels to get more verbose output. But I would start by confirming that there are some resources that `kubent` should return, first.


[^1]: https://github.com/doitintl/kube-no-trouble/blob/d1bb4e5fd6550b533b2013671aa8419d923ee042/pkg/collector/cluster.go#L74-L109
