### ISSUE TITLE
failed to discover supported resources

### ISSUE THREAD

**Issue by autumnw** [doitintl/kube-no-trouble#429]
When I run kubent over one of my AWS EKS clusters, I got lots of the warming messages:
```
11:20AM WRN failed to discover supported resources for catalog.kubedb.com/v1alpha1: the server could not find the requested resource
11:20AM WRN failed to discover supported resources for catalog.kubedb.com/v1alpha1: the server could not find the requested resource
11:20AM WRN failed to discover supported resources for catalog.kubedb.com/v1alpha1: the server could not find the requested resource
11:21AM WRN failed to discover supported resources for apps/v1beta1: the server could not find the requested resource
11:21AM WRN failed to discover supported resources for apps/v1beta1: the server could not find the requested resource
```
And keep running for long long time without results.

**Comment by autumnw** [comment]
BTW, here is the detail information of my EKS cluster:

awang@066647af0c22:~/.kube$ kubent
11:18AM INF >>> Kube No Trouble `kubent` <<<
11:18AM INF version 0.7.0 (git sha d1bb4e5fd6550b533b2013671aa8419d923ee042)
11:18AM INF Initializing collectors and retrieving data
11:18AM INF Target K8s version is 1.21.14-eks-fb459a0
11:19AM INF Retrieved 91 resources from collector name=Cluster

**Comment by stepanstipl** [comment]
Hi @autumnw, thanks for reporting this 👍. This would likely mean that you have some old Helm manifests which are either not used/or have been updated in-cluster while the Helm release manifests still contain old API versions.

For start, are you using Helm?

And can you please try to run kubent with the `-l debug` to increase logging, and share output around one or two of those errors? This should give us a hint about the problematic resource(s) 🤞.

**Comment by odu14ick** [comment]
Hi @stepanstipl having the same issue. Indeed we are using Helm, or, more precisely, helm_release terraform provider. 

And naturally, we do have a lot of older manifests with the older API versions specified. Some of those were since updated to the newer API versions, some weren't. All of those are still in the kubent's output.

Unfortunately the NDA policy at my company does not make it very clear if I can share the corresponding manifests with some company info (microservice names, secret names, etc). But I'm positive this comes from the older manifests (stored as k8s secrets in my case).

For instance something like this (obfuscated) comes  up in debug logs:
```
DBG retrieved: /%resource_name% (policy/v1beta1, Kind=PodDisruptionBudget)
WRN failed to discover supported resources for policy/v1beta1: the server could not find the requested resource
```

Because, naturally the latest helm release version already has the updated API version.

So the question now is if there's actually a way to make kubent explicitly consider the latest helm release manifest / version only?

Thank you!

**Comment by odu14ick** [comment]
My bad, actually.

After investigating some more I found the following:
we do still have the deprecated APIs listed in the latest release manifests. Apparently GKE just converted the k8s objects themselves to the current API versions.

After updating the version in the latest Helm release manifest kubent no longer detects the resource as affected.

Sorry for misinforming, everyone.

**Comment by stepanstipl** [comment]
@odu14ick glad to hear you managed to resolve this 👍 . And yes, kubent collects and checks only Helm manifests that are in `deployed` state, i.e. it should've just the latest one typically.

**Comment by stepanstipl** [comment]
Since we haven't heard back for a while. @autumnw please reopen if this is still the issue and not fixed by the above. Cheers
