### ISSUE TITLE
GKE - Some of the GKE Deprecated API's are not visible.

### ISSUE THREAD

**Issue by ishanrakitha** [doitintl/kube-no-trouble#451]
Hi All,

I'm seeing two different sets of API's in Kubent & GKE console. 
Please advise. Appreciate your support in advance. 

![kubent](https://user-images.githubusercontent.com/3178753/220296696-42316c15-0aae-45e9-b90e-4be49f84ca9a.jpg)
![GKE](https://user-images.githubusercontent.com/3178753/220296654-ca3585e4-2f48-4915-9dec-72f7bc5e91bc.JPG)

Thank You.

**Comment by stepanstipl** [comment]
Hi @ishanrakitha, this is expected as the `kubent` and recommendations in GKE console operate on different principles.

The GKE API deprecations[^1] work by analyzing calls against the K8S API, and if a call against deprecated API is found within last 30 days, it will be flagged. As such, it will detect various operators and other clients using the old APIs. However, this approach will not catch, for example, resources created a while ago using the old API version and not touched since.

`kubent`, on the other hand, relies on `last-applied-configuration` annotation (or Helm rendered manifests). I.e. it tries to understand how resources were created, but doesn't know anything about current API usage. So while it will likely catch old API from the previously mentioned scenario, it won't see if there's, for example, an operator/controller deployed in your cluster still using the old APIs.

I.e. GKE Console sees what is happening now, `kubent` how the resources were created. In that sense, the tools are complementary, and I would recommend resolving issues from both before upgrading (some can overlap).

I hope that makes sense 😄.

[^1]: https://cloud.google.com/kubernetes-engine/docs/deprecations
