### ISSUE TITLE
Multi Tenant Shared EKS cluster 

### ISSUE THREAD

**Issue by tppalani** [doitintl/kube-no-trouble#507]
We are running Shared EKS cluster based on the namespace level, let's say we have application team A, we will create deticated namespace and the application team will deploy their workload only respective namespace.

I ordered to find depricated value, do we have any bash script to list out api?

**Comment by stepanstipl** [comment]
> I ordered to find depricated value, do we have any bash script to list out api?

Hi @tppalani, sorry, but I'm not sure I understand the question. If you want to filter results only for certain namespace, you can use `kubent` with json/yaml output - `-o` flag:
```
 -o, --output string                   output format - [text|json|csv] (default "text")
```

and filter the results. Otherwise, `kubent` itself will currently run on the whole cluster and try to collect all resources.
