### ISSUE TITLE
Entries appear that are not in config

### ISSUE THREAD

**Issue by davejhahn** [doitintl/kube-no-trouble#509]
I see that it picks up Last configuration, which I can live with.   But,  when I run this I get results listed that are just not there anywhere.

e.g.
kubent --target-version 1.25.6

One of the groups is deprecated APIs removed in 1.26 with 3 entries for _autoscaling/v2beta2 -> autoscaling/v2_

However, the three resources listed have zero reference to v2beta2 or even "beta" at all.   So really puzzled why it is showing these.

It seems that either I am misunderstanding how this works or it is producing invalid results.

**Comment by ewertonhm** [comment]
I have the same issue here, we have a cluster in kubernetes 1.20, the kubent show ingresses that needs to go from extension/v1beta1 to networking.k8s.io/v1 before upgrating to 1.22, but when I do a "kubectl edit ingress "xpto", they are already in the networking.k8s.io/v1 version... 
![kubent](https://github.com/doitintl/kube-no-trouble/assets/30476434/920b66b9-ed21-43f8-be82-54c9a268eff3)

![image](https://github.com/doitintl/kube-no-trouble/assets/30476434/468c572e-2b5d-4daf-933b-6cc64d257126)

**Comment by nwe01** [comment]
We also  hit the same issues with HorizontalPodAutoscaler

We are running autoscaling/v2 while the tool reports we have autoscaling/v2beta2

`KIND                      NAMESPACE           NAME                      API_VERSION           REPLACE_WITH (SINCE)`
`HorizontalPodAutoscaler   ingress-internal    nginx-ingress-internal    autoscaling/v2beta2   autoscaling/v2 (1.23.0)`

`kubectl get hpa nginx-ingress-internal -n ingress-internal -o yaml|grep ^api`
`apiVersion: autoscaling/v2`

**Comment by stepanstipl** [comment]
Hi everyone - this, and why it's not possible to tell anything by just running `kubectl get` and looking at the `apiVersion` property, has been discussed a couple of times. Please have a look at [^1] for example, where I go more in detail.

If you believe this is not the case, feel free to comment why not.


I have, however, created an issue to add an FAQ section, as this is a common misconception #528.

[^1]: https://github.com/doitintl/kube-no-trouble/issues/316#issuecomment-1245335960

**Comment by madAndroid** [comment]
@stepanstipl  - thanks for the explanation, I can understand the choice to use `last-applied-configuration` annotation, but unfortunately we've seen that in practise, this doesn't always match the current state of the resource - our assumption currently is that this is due to ArgoCD using server-side-apply to update resources, and that _doesn't_ update the `last-applied-configuration` annotation, leading to the same symptoms as others have seen in this and other posted issues.
